# Generated by Django 2.1.5 on 2019-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('nId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('nTitle', models.CharField(max_length=100, null=True, verbose_name='摘要')),
                ('nContent', models.TextField(verbose_name='正文')),
                ('nCategory', models.CharField(choices=[('l', '生活'), ('t', '技术'), ('e', '经济')], max_length=1)),
                ('nTag', models.TextField(max_length=50, null=True, verbose_name='标签')),
                ('nCreateTime', models.DateTimeField(verbose_name='创建时间')),
                ('nUpdateTime', models.DateTimeField(verbose_name='更新时间')),
                ('nView', models.IntegerField(default=0, verbose_name='阅读量')),
                ('nLike', models.IntegerField(default=0, verbose_name='点赞量')),
                ('nIsDeleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('nIsPublic', models.BooleanField(default=False, verbose_name='公开可见')),
            ],
        ),
    ]
