# Generated by Django 2.1.5 on 2019-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='nPicUrl',
            field=models.CharField(max_length=100, null=True, verbose_name='图片'),
        ),
    ]
