# Generated by Django 2.1.5 on 2019-01-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190131_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
